python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 737 --log-events raw_events/log00.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 177 --log-events raw_events/log01.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 50 --log-events raw_events/log02.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 797 --log-events raw_events/log03.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 569 --log-events raw_events/log04.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 869 --log-events raw_events/log05.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 202 --log-events raw_events/log06.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 15 --log-events raw_events/log07.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 301 --log-events raw_events/log08.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 745 --log-events raw_events/log09.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 740 --log-events raw_events/log10.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 748 --log-events raw_events/log11.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 864 --log-events raw_events/log12.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 170 --log-events raw_events/log13.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 830 --log-events raw_events/log14.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 723 --log-events raw_events/log15.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 194 --log-events raw_events/log16.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 212 --log-events raw_events/log17.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 690 --log-events raw_events/log18.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 512 --log-events raw_events/log19.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 637 --log-events raw_events/log20.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 276 --log-events raw_events/log21.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 817 --log-events raw_events/log22.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 768 --log-events raw_events/log23.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 578 --log-events raw_events/log24.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 788 --log-events raw_events/log25.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 65 --log-events raw_events/log26.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 909 --log-events raw_events/log27.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 804 --log-events raw_events/log28.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 513 --log-events raw_events/log29.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 695 --log-events raw_events/log30.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 316 --log-events raw_events/log31.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 939 --log-events raw_events/log32.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 999 --log-events raw_events/log33.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 533 --log-events raw_events/log34.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 151 --log-events raw_events/log35.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 899 --log-events raw_events/log36.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 6 --log-events raw_events/log37.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 656 --log-events raw_events/log38.csv
python simRec.py genome_chrII.csv --n-gen 20 --p-rec 3e-7 --seed 56 --log-events raw_events/log39.csv
