python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set00.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set01.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set02.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set03.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set04.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set05.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set06.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set07.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set08.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set09.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set10.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set11.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set12.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set13.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set14.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set15.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set16.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set17.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set18.tsv
python simRec_batch.py genome_chrII.csv --n-cells 88 --n-gen 3000 --co-nco 0.5 --out batch_update/set19.tsv
